name: Build SD Webui Container

on:
  workflow_dispatch:
    inputs:
      build:
        type: choice
        description: "Release build"
        default: "dev"
        required: true
        options:
          - latest
          - dev
          - test
      date:
        description: "Date version"
        default: "2024.09.21"
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Set Docker Tag
        id: set_tag
        run: |
          build="${{github.event.inputs.build}}"
          date="${{github.event.inputs.date}}"
          base_tag="${{secrets.DOCKER_USER}}/sd-webui-containers:auto1111"
          build_tag="$base_tag-$build"
          
          if [ "$build" == "test" ]; then
            echo "tags=$build_tag" >> $GITHUB_ENV
          else
            if [ "$build" == "dev" ]; then
              date_tag="$build_tag-$date"
            elif [ "$build" == "latest" ]; then
              date_tag="$base_tag-$date"
            fi
            echo "tags=$build_tag,$date_tag" >> $GITHUB_ENV
          fi

      - name: Build and Publish to Docker Hub
        uses: docker/build-push-action@v4
        with:
          file: sd-webui/Dockerfile
          tags: ${{env.tags}}
          push: true